
# This is a basic workflow to help you get started with Actions

name: CIHOGE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: pip install slackweb
      - name: js diff check
        run: |
          BEFORE_SHA=$(jq -r '.before' $GITHUB_EVENT_PATH)
          AFTER_SHA=$(jq -r '.after' $GITHUB_EVENT_PATH)
          add=`git diff --name-only --diff-filter=A ${BEFORE_SHA}..${AFTER_SHA} -- oui/stories/**`
          del=`git diff --name-only --diff-filter=D ${BEFORE_SHA}..${AFTER_SHA} -- oui/stories/**`
          if [ -n "$add" ] || [ -n "$del" ]; then
            report="storybookに
            ${add}
            が追加され、
            ${del}
            が削除されました。"
            python send_slack.py --message $report | tr ' ' '\n'
          fi